
test_homogen_basics.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall test_homogen_basics.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_homogen_basics.exe 


test_poly_mul_sweeper.exe: ../obj/*cc.o ../obj/poly_utils.o 
	c++ -Wall test_poly_mul_sweeper.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_poly_mul_sweeper.exe 


test_remove_zeros.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall test_remove_zeros.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_remove_zeros.exe 

test_eval_and_mul.exe:  ../obj/*cc.o ../obj/poly_utils.o.o
	c++ -Wall -DDEBUG test_eval_and_mul.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_eval_and_mul.exe 

test_mul_seq.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_mul_seq.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_mul_seq.exe 

test_term_comp.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_term_comp.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_term_comp.exe 

test_order_iteration.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_order_iteration.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_order_iteration.exe 

test_matrix_mul.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_matrix_mul.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_matrix_mul.exe 

test_derivative.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_derivative.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_derivative.exe 

test_series_derivative_dot.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_series_derivative_dot.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_series_derivative_dot.exe 


test_series_sq.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_series_sq.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_series_sq.exe 


test_series_to_linked_list.exe:  ../obj/*cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_series_to_linked_list.cpp ../obj/*cc.o ../obj/poly_utils.o -o test_series_to_linked_list.exe 

test_memory.exe: ../obj/polys_cc.o ../obj/poly_utils.o
	c++ -Wall -DDEBUG test_memory.cpp ../obj/polys_cc.o ../obj/poly_utils.o -o test_memory.exe -g


