
test_homogen_basics.exe:  ../obj/polys.o
	c++ -Wall test_homogen_basics.cpp ../obj/polys.o -o test_homogen_basics.exe 


test_poly_mul_sweeper.exe:  ../obj/polys.o
	c++ -Wall test_poly_mul_sweeper.cpp ../obj/polys.o -o test_poly_mul_sweeper.exe 


test_remove_zeros.exe:  ../obj/polys.o
	c++ -Wall test_remove_zeros.cpp ../obj/polys.o -o test_remove_zeros.exe 

test_eval_and_mul.exe:  ../obj/polys.o
	c++ -Wall -DDEBUG test_eval_and_mul.cpp ../obj/polys.o -o test_eval_and_mul.exe 
